name: ci

on: [push]

jobs:
  compile:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - rust: stable
          # - rust: nightly

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          components: llvm-tools-preview

      - name: install cargo-binutils
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-binutils
          toolchain: ${{ matrix.rust }}

      - name: program size
        uses: actions-rs/cargo@v1
        with:
          command: size
          args: --release
          toolchain: ${{ matrix.rust }}

      - name: lint
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
